"""fk fix

Revision ID: d9be55a297e7
Revises: 71f85853ad00
Create Date: 2024-11-15 23:14:50.481510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9be55a297e7'
down_revision: Union[str, None] = '71f85853ad00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=False, comment='Время готовки в минутах'),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reciepts')
    op.add_column('ingredients', sa.Column('receipt_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'receipt_id')
    op.create_table('reciepts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cooking_time', sa.INTEGER(), autoincrement=False, nullable=False, comment='Время готовки в минутах'),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reciepts_pkey')
    )
    op.drop_table('receipts')
    # ### end Alembic commands ###
